FROM golang:1.25-alpine AS build

RUN apk add --no-cache bash make netcat-openbsd postgresql-client

WORKDIR /app
COPY . .
RUN go build -o /usr/bin/migrations ./cmd/migrations

COPY ./migrations /app/migrations
WORKDIR /app
